# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le script
COPY ingestion/ ./ingestion/

# Lancer le script
CMD ["python", "ingestion/youtube_producer.py"]
