# Dockerfile.spark
FROM apache/spark:3.5.1

USER root

# Installer psycopg2 pour PostgreSQL
RUN apt-get update && \
    pip3 install --no-cache-dir psycopg2-binary

WORKDIR /opt/spark/work-dir
COPY spark_jobs/ ./spark_jobs/

CMD ["/opt/spark/bin/spark-submit","--packages", "org.postgresql:postgresql:42.6.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1","/opt/spark/work-dir/spark_jobs/batch_transform.py"]